### ISSUE TITLE
Doesn't load any asset

### ISSUE THREAD

**Issue by neoacevedo** [charlesportwoodii/yii2-analytics.js#1]
Once installed, it simply doesn't load any analytics asset.

**Comment by charlesportwoodii** [comment]
@neoacevedo,

To be entirely honest this package hasn't been touched in over 3 years now. Glancing at the composer dependencies, it looks like `bower-asset/analytics`, one of the upstream dependencies has been deleted.

I can take a look in a couple of days time pending, however in 3 years Segment.io has released multiple updates. This package probably doesn't work anymore in it's current state.

Segment now has a PHP library anyways that would supersede this https://segment.com/docs/sources/server/php/. I would take a look at that if you need in-app analytics, or integrate their analytics.js file directly.
